### ISSUE TITLE
Move deploy and contract creation to beforeEach()

### ISSUE THREAD

**Issue by shaharyakir** [ton-community/blueprint#12]
It would make more sense that the test template creates the contract within a `beforeEach` hook instead of a separate test, because most tests would need a deployed contract ready to use.

```
describe('MyContract', () => {
    let code: Cell;
    let contract: OpenedContract<MyContract>;
    let blockchain: Blockchain;

    beforeAll(async () => {
        code = await compile('MyContract');
    });

    beforeEach(async () => {
        blockchain = await Blockchain.create();
        contract = blockchain.openContract(
            MyContract.createFromConfig({}, code)
        );
        const deployer = await blockchain.treasury('deployer');
        const deployResult = await replayAttack.sendDeploy(deployer.getSender(), toNano('0.05'));

        expect(deployResult.transactions).toHaveTransaction({
            from: deployer.address,
            to: replayAttack.address,
            deploy: true,
        });
    });

...
```

**Comment by krigga** [comment]
Do `expect` calls work correctly in `beforeEach`?

**Comment by shaharyakir** [comment]
They seem to (Stack traces are off, but that happens also with regular tests), but if it's too unorthodox, we can instead extract deployment to a function that's by both the default test and the beforeEach hook.

**Comment by talkol** [comment]
When somebody is writing 20 tests, they will need to deploy once in beforeAll so we need this refactor.

**Comment by krigga** [comment]
Done in v0.3.0
