### ISSUE TITLE
OpenedContract should be imported from ton-core

### ISSUE THREAD

**Issue by shaharyakir** [ton-community/blueprint#13]
ton-core exports the `OpenedContract` type (since 0.46.0). 
1. Sandbox shouldn't export it
2. The test template should import from ton-core

**Comment by krigga** [comment]
The `OpenedContract` type from sandbox is different from the one in ton-core, and this is necessary to provide some features. However, it might be a good idea to rename it to something like `SandboxContract`

**Comment by shaharyakir** [comment]
Can you elaborate? (Perhaps that's an indication that something needs to change in ton-core to support these features?)

**Comment by krigga** [comment]
`OpenedContract` from sandbox:
```typescript
export type OpenedContract<F> = {
    [P in keyof F]: P extends `get${string}`
        ? (F[P] extends (x: ContractProvider, ...args: infer P) => infer R ? (...args: P) => R : never)
        : (P extends `send${string}`
            ? (F[P] extends (x: ContractProvider, ...args: infer P) => infer R ? (...args: P) => Promise<SendMessageResult & {
                result: R extends Promise<infer PR> ? PR : R
            }> : never)
            : F[P]);
}
```
from ton-core:
```typescript
type OpenedContract<F> = {
    [P in keyof F]: P extends `${'get' | 'send'}${string}` ? (F[P] extends (x: ContractProvider, ...args: infer P) => infer R ? (...args: P) => R : never) : F[P];
};
```
As you can see, results from `send*` methods get augmented by sandbox-specific results with the sandbox variant. It's necessary for a smooth unit testing experience.
