### ISSUE TITLE
Deployer sender does not support `bounce` and `sendMode` restriction

### ISSUE THREAD

**Issue by anstill** [ton-community/blueprint#2]
Is support expected for `bounce` messages and different `sendMode` in the future?

**Comment by krigga** [comment]
Please see https://github.com/ton-community/blueprint/pull/3#issuecomment-1423877869 and further discussion

Non-default `bounce` and `sendMode` cannot really be supported in the current state of things. If this restriction becomes a big pain, the checks will probably become configurable `console.warn`s or something like that. For now, I'm closing this, please open a new issue if this or something similar bothers you again.
