### ISSUE TITLE
Deprecate `provider.deploy` in favor of `waitDeploy`

### ISSUE THREAD

**Issue by talkol** [ton-community/blueprint#20]
The goal is to standardize the deployment between sandbox, ton library and now blueprint. We teach the developers to create `sendDeploy()` in their wrapper for the deployment and then we don't use it in blueprint.

old code:

```ts
export async function run(provider: NetworkProvider) {
    const counter = Counter.createFromConfig({}, await compile('Counter'));
    await provider.deploy(counter, toNano('0.05'));
    const openedContract = provider.open(counter);
    // run methods on `openedContract`
}
```

new code:

```ts
export async function run(provider: NetworkProvider) {
    const contract = Counter.createFromConfig({}, await compile('Counter'))
    if (await provider.isContractDeployed(contract.address)) {
      // print already deployed and exit
    }
    const counter = provider.open(contract);
    await counter.sendDeploy(provider.sender(), toNano('0.05'));
    await provider.waitDeployed(counter);    
}
```

This exposes some smells with naming. The name for `provider: NetworkProvider` is confusing in the run function. This argument resembles `ton` library's `TonClient` more than anything. The name should probably be changed to `client: NetworkClient` and then the code will be nearly identical to `ton` library with `client.isContractDeployed` and `client.open`.

**Comment by krigga** [comment]
Done in v0.3.0
