### ISSUE TITLE
Error while using Approve in your wallet option for scripts for write operations on chain

### ISSUE THREAD

**Issue by tuminzee** [ton-community/blueprint#43]
Whenever I try to use blueprint ts scripts to perform actions using the option
`TON Connect compatible mobile wallet (example: Tonkeeper)` 

Requests for txs are not being displayed on TONKeeper, but read only operations are performed without any hiccups

Is there anything which I can do to resolve this?
I usually give up after 3 tries, and scan the code for tx and perform the action manually

**Comment by braveltd** [comment]
Are you sure you don't connected to tonconnect via different network?

**Comment by tuminzee** [comment]
I was connected to the testnet
I will create and attach recording of the error for your reference
thank you for your time

**Comment by tuminzee** [comment]
@braveltd sorry for troubles
I tried recording a videos, but weirdly it got solved 
I was able to get approval requests on my wallet
thank you anyways


I will close this issue, it doesn't require any support
