### ISSUE TITLE
New contract template does not create imports and stdlib.fc

### ISSUE THREAD

**Issue by talkol** [ton-community/blueprint#6]
So the new project does not compile

**Comment by Gusarich** [comment]
```
Error: Func compilation error: contracts/test_contract.fc:1:1: error: ENOENT: no such file or directory, open 'contracts/imports/stdlib.fc'
  #include "imports/stdlib.fc"; ;; import the stdlib to have access to all standard functions

```

**Comment by krigga** [comment]
Fixed in https://github.com/ton-community/create-ton/commit/b7c816b0bde85e9041c77e00fa80715df245706b. Users are advised to upgrade to the latest version of create-ton (done automatically when using `npm create ton@latest`), which is 0.0.9 at the time of writing
